Make InboundHAProxyHandler @Sharable (#2233)
#2205 introduces a regression where multiple uses of HAProxyProtocolDetectingDecoder::decode will now end with Exception:
io.netty.channel.ChannelPipelineException: org.apache.cassandra.stargate.transport.internal.HAProxyProtocolDetectingDecoder is not a @Sharable handler, so can't be added or removed multiple times.

Since InboundHAProxyHandler looks reentrant and because the original idea behind #2205 was to make it shared let's do just that