STAR-157 parent pom build fix (#676)
* STAR-157 add missing module in the parent pom

testing module requires testing-services module

* STAR-157 add --bind-to-listen-address to starctl cmd in dev guide

Without this flag stargate tries to bind to 0.0.0.0:9042 and fails

java.lang.IllegalStateException: Failed to bind port 9042 on 0.0.0.0.

With the flag stargate correctly binds to listen address:

tcp6       0      0 127.0.0.2:9042          :::*                    LISTEN